2015-09-02 10:08:43,811 [Thread-56:5416] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 222, in tag
    paginator = Paginator(article_list, 10)
UnboundLocalError: local variable 'article_list' referenced before assignment
2015-09-02 10:09:10,928 [Thread-57:6892] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 222, in tag
    paginator = Paginator(article_list, 10)
UnboundLocalError: local variable 'article_list' referenced before assignment
2015-09-02 10:10:11,213 [Thread-65:4384] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 222, in tag
    paginator = Paginator(article_list, 10)
UnboundLocalError: local variable 'article_list' referenced before assignment
2015-09-02 10:10:13,299 [Thread-66:6084] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 222, in tag
    paginator = Paginator(article_list, 10)
UnboundLocalError: local variable 'article_list' referenced before assignment
2015-09-02 10:11:37,507 [Thread-2:6876] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 222, in tag
    article_list = getPage(request, article_list)
UnboundLocalError: local variable 'article_list' referenced before assignment
2015-09-02 10:13:03,167 [Thread-45:4760] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 217, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\Python27\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'endblock', expected 'empty' or 'endfor'
2015-09-02 10:21:14,401 [Thread-98:2740] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 217, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\Python27\lib\site-packages\django\template\base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 639, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '[id].name' from 'tag[id].name'
2015-09-02 10:21:48,072 [Thread-99:7040] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 217, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\Python27\lib\site-packages\django\template\base.py", line 315, in parse
    self.empty_variable(token)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 386, in empty_variable
    raise self.error(token, "Empty variable tag")
TemplateSyntaxError: Empty variable tag
2015-09-02 10:24:42,605 [Thread-2:7076] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 219, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "D:\Python27\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'endfor', expected 'elif', 'else' or 'endif'
2015-09-02 10:27:07,436 [Thread-2:4892] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 216, in tag
    tag_list = Tag.objects.all()[id]
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 177, in __getitem__
    raise TypeError
TypeError
2015-09-02 10:27:54,440 [Thread-2:7076] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 219, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Tag' object is not iterable
2015-09-02 10:28:41,693 [Thread-3:6944] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 219, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Tag' object is not iterable
2015-09-02 10:29:21,049 [Thread-4:6088] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 219, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Tag' object is not iterable
2015-09-02 10:29:23,107 [Thread-5:5436] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 219, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Tag' object is not iterable
2015-09-02 10:29:23,378 [Thread-6:6224] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 219, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Tag' object is not iterable
2015-09-02 10:29:23,665 [Thread-7:5392] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 219, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Tag' object is not iterable
2015-09-02 10:29:32,585 [Thread-9:7152] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 219, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Tag' object is not iterable
2015-09-02 10:29:52,349 [Thread-10:1048] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 219, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Tag' object is not iterable
2015-09-02 10:30:33,104 [Thread-11:3768] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 219, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Tag' object is not iterable
2015-09-02 10:42:31,339 [Thread-3:6104] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 219, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Tag' object is not iterable
2015-09-02 10:43:44,130 [Thread-20:724] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 219, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Tag' object is not iterable
2015-09-02 10:46:26,890 [Thread-21:5868] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 219, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Tag' object is not iterable
2015-09-02 10:47:11,368 [Thread-2:4508] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 218, in tag
    return render(request,'tag.html',locals())
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Tag' object is not iterable
2015-09-02 10:53:18,934 [Thread-2:744] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 217, in tag
    article_tag_list = Article.objects.get(pk=name)
  File "D:\Python27\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Article matching query does not exist.
2015-09-02 10:55:17,167 [Thread-2:1660] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 217, in tag
    article_tag_list = Article.objects.get(name=name)
  File "D:\Python27\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 325, in get
    clone = self.filter(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1309, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1337, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1396, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'name' into field. Choices are: category, category_id, click_count, comment, content, date_publish, desc, id, is_recommend, tag, title, user, user_id
2015-09-02 10:56:01,561 [Thread-2:3808] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 217, in tag
    article_tag_list = Article.objects.get(pk=tag['name'])
TypeError: 'Tag' object has no attribute '__getitem__'
2015-09-02 10:56:11,473 [Thread-2:4864] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 217, in tag
    article_tag_list = Article.objects.get(pk=tag[name])
TypeError: 'Tag' object has no attribute '__getitem__'
2015-09-02 10:56:41,078 [Thread-2:6396] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 217, in tag
    article_tag_list = Article.objects.values('name')
  File "D:\Python27\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 606, in values
    return self._clone(klass=ValuesQuerySet, setup=True, _fields=fields)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 960, in _clone
    c._setup_query()
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 1136, in _setup_query
    self.query.add_fields(self.field_names, True)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1712, in add_fields
    "Choices are: %s" % (name, ", ".join(names)))
FieldError: Cannot resolve keyword 'name' into field. Choices are: category, category_id, click_count, comment, content, date_publish, desc, id, is_recommend, tag, title, user, user_id
2015-09-02 10:58:46,313 [Thread-2:1824] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 217, in tag
    article_tag_list = Article.objects.filter(name=name)
  File "D:\Python27\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1309, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1337, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1396, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'name' into field. Choices are: category, category_id, click_count, comment, content, date_publish, desc, id, is_recommend, tag, title, user, user_id
2015-09-02 10:58:47,391 [Thread-3:5992] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /tag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python_blog\python_blog\blog\views.py", line 217, in tag
    article_tag_list = Article.objects.filter(name=name)
  File "D:\Python27\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1309, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1337, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1396, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'name' into field. Choices are: category, category_id, click_count, comment, content, date_publish, desc, id, is_recommend, tag, title, user, user_id
2015-09-02 11:29:46,052 [Thread-272:6620] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2015-09-02 11:29:46,065 [Thread-273:5996] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2015-09-02 12:00:11,289 [Thread-502:6076] [django.request:170] [base:get_response] [WARNING]- Not Found: /article/direct
2015-09-02 12:00:18,667 [Thread-503:6080] [django.request:170] [base:get_response] [WARNING]- Not Found: /article/about
2015-09-02 12:19:35,914 [Thread-537:3800] [django.request:170] [base:get_response] [WARNING]- Not Found: /article/direct
2015-09-02 14:37:22,032 [Thread-3:6492] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2015-09-02 14:37:22,039 [Thread-4:1196] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2015-09-02 16:31:01,966 [Thread-9:2164] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2015-09-02 16:31:01,973 [Thread-10:6724] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2015-09-02 16:35:05,434 [Thread-2:2892] [django.request:170] [base:get_response] [WARNING]- Not Found: /message
